### ISSUE TITLE
ready to fork?

### ISSUE THREAD

**Issue by BarkleyBG** [bsaul/bios_masters_template#1]
I'd like to fork this into @tarheelbiostatistics, which may be a more convenient location for future students. Would you mind? Do you have any updates to push before it gets forked?

Thanks!

**Comment by bsaul** [comment]
Go for it. Once forked, I can put a note up on my repository pointing
people to the @TarHeelBiostatistics repository.

**Comment by BarkleyBG** [comment]
Learning experience for @djluckett @phoebejiang @cttnguyen!

**Comment by BarkleyBG** [comment]
We will fork once #2 is finished. Please notify Daniel, Phoebe and Crystal above when you close #2.

**Comment by phoebejiang** [comment]
We forked it. Thanks!
